# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'i:\Python\git\元素定位\qttest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 2, 1, 1, QtCore.Qt.AlignTop)
        self.JieImg = QtWidgets.QPushButton(self.centralwidget)
        self.JieImg.setObjectName("JieImg")
        self.gridLayout.addWidget(self.JieImg, 1, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 2, 2, 1, 1)
        self.myRPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.myRPlainTextEdit.setObjectName("myRPlainTextEdit")
        self.gridLayout.addWidget(self.myRPlainTextEdit, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.JieImg.clicked.connect(self.myRPlainTextEdit.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeepAiImagePosigion"))
        self.progressBar.setToolTip(_translate("MainWindow", "<html><head/><body><p>进度条</p></body></html>"))
        self.JieImg.setText(_translate("MainWindow", "截图"))
        self.myRPlainTextEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>这是源数据表</p></body></html>"))
